FROM node:latest

WORKDIR /app/client

ENV PATH /app/client/node_modules/.bin:$PATH

COPY package.json /app/client/package.json

RUN npm install --silent

COPY . /app/client

RUN npm run build

FROM nginx

COPY --from=build /app/client/build /app/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/

CMD ["nginx", "-g"]

