version: "3"

services:
  web:
    build:
      context: ./api/
      dockerfile: Dockerfile.production
    container_name: flaskapp
    tty: true
    volumes:
      - ./api:/app/api/
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production

  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host

  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/prod_mysql_data:/var/lib/mysql
      - ./mysql/prod_sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "4306:3306"
  client:
    build: ./client/
    stdin_open: true
    volumes:
      - "./client:/app/client/"
      - "/app/client/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    links:
      - web

networks:
  default:
    driver: bridge
