version: "3"

services:
  web:
    build:
      context: ./api/
      dockerfile: Dockerfile.test
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - ./api:/app/api/
    environment:
      - FLASK_CONFIG=test
      - FLASK_ENV=test
