version: "3"

services:
  web:
    build: ./api/
    dockerfile: Dockerfile.production
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./api:/app/api/
    environment:
      FLASK_APP: run.py
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/prod_mysql_data:/var/lib/mysql
      - ./mysql/prod_sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "4306:3306"
  client:
    build: ./client/
    stdin_open: true
    volumes:
      - "./client:/app/client/"
      - "/app/client/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    links:
      - web
