version: "3"

services:
  web:
    build:
      context: ./api/
      dockerfile: Dockerfile.production
    container_name: backend
    expose:
      - "5000"
    command: bash -c "flask db migrate && flask db upgrade"
    tty: true
    volumes:
      - ./api:/app/api/
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    restart: always

  mysql:
    build: ./mysql/
    container_name: mysql
    volumes:
      - ./mysql/prod_mysql_data:/var/lib/mysql
      - ./mysql/prod_sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "4306:3306"

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.production
    container_name: frontend
    stdin_open: true
    environment:
      - SERVER_NAME=0.0.0.0
      - NODE_ENV=production
    volumes:
      - "./client:/app/client/"
      - "/app/client/node_modules"
    ports:
      - "80:80"
