pipeline {
    agent any

    stages {
        stage("Build") {
            steps {
                sh " /var/jenkins_home/workspace/cryptocurrency-portfolio-ci-cd-pipline/pipeline/build.sh"
            }
        }    
    }
}