FROM python:3.6


WORKDIR /app/api
COPY . /app/api/

ENV FLASK_CONFIG=test
ENV FLASK_ENV=test

EXPOSE 5000


RUN pip install --upgrade pip
RUN pip install coverage
RUN pip3 install -r requirements.txt


